---
baseURL: "https://sockets.fr/"
title: "Sockets"

languageCode: "fr-fr"

metaDataFormat: "yaml"

taxonomies:
  city: "cities"
  category: "categories"
  speedrate: "speedrates"
  tag: "tags"
  day: "days"

preserveTaxonomyNames: true  

params:
  author: "Wassim Bourguiba"
  description: "Collection d\'espaces gratuits pour travailler en ligne."
  copyright: "Copyright (c) {year}. Site construit avec <a href=\"https://gohugo.io/\" title=\"Hugo\">Hugo</a> par <a href=\"https://wassim.site/\" title=\"Wassim\">Wassim</a>. Voir le <a href=\"https://github.com/wassim\" title=\"Voir le code source\">code source</a>."
---