---
baseURL: "https://sockets.ext/"
title: "Sockets"

languageCode: "en-us"

metaDataFormat: "yaml"

taxonomies:
  city: "cities"
  category: "categories"
  speed-tag: "speed-tags"
  tag: "tags"
  day: "days"

preserveTaxonomyNames: true  

params:
  author: "Wassim Bourguiba"
  description: "A list of awesome free spaces to work online in France."
  copyright: "Copyright (c) {year}. Built with <a href=\"https://gohugo.io/\" title=\"Hugo\">Hugo</a> by <a href=\"https://wassim.site/\" title=\"Wassim\">Wassim</a>. View source code."
---